//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.12 at 12:44:54 AM EST 
//


package https.www_advantageonlinebanking_com.shipex;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_advantageonlinebanking_com.shipex package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_advantageonlinebanking_com.shipex
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlaceShippingOrderResponse }
     * 
     */
    public PlaceShippingOrderResponse createPlaceShippingOrderResponse() {
        return new PlaceShippingOrderResponse();
    }

    /**
     * Create an instance of {@link TrackNumberResponse }
     * 
     */
    public TrackNumberResponse createTrackNumberResponse() {
        return new TrackNumberResponse();
    }

    /**
     * Create an instance of {@link TrackNumberRequest }
     * 
     */
    public TrackNumberRequest createTrackNumberRequest() {
        return new TrackNumberRequest();
    }

    /**
     * Create an instance of {@link ShippingCostResponse }
     * 
     */
    public ShippingCostResponse createShippingCostResponse() {
        return new ShippingCostResponse();
    }

    /**
     * Create an instance of {@link PlaceShippingOrderRequest }
     * 
     */
    public PlaceShippingOrderRequest createPlaceShippingOrderRequest() {
        return new PlaceShippingOrderRequest();
    }

    /**
     * Create an instance of {@link SEAddress }
     * 
     */
    public SEAddress createSEAddress() {
        return new SEAddress();
    }

    /**
     * Create an instance of {@link SEProducts }
     * 
     */
    public SEProducts createSEProducts() {
        return new SEProducts();
    }

    /**
     * Create an instance of {@link ShippingCostRequest }
     * 
     */
    public ShippingCostRequest createShippingCostRequest() {
        return new ShippingCostRequest();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

}
