apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: devops-aos-prd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: db-postgresql
    spec:
      containers:
      - name: db
        image: app-registry:30005/postgresql:adm-db
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 128Mi
      nodeSelector:
        devops.node.pool: static
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mastercredit-deployment
  namespace: devops-aos-prd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-mastercredit
    spec:
      containers:
      - name: mastercredit
        image: app-registry:30005/mastercredit:latest
        env:
        - name: CATALINA_OPTS
          value: "-Xms256M -Xmx1024M"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1G
      nodeSelector:
        devops.node.pool: static
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: safepay-deployment
  namespace: devops-aos-prd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-safepay
    spec:
      containers:
      - name: safepay
        image: app-registry:30005/safepay:latest
        env:
        - name: CATALINA_OPTS
          value: "-Xms256M -Xmx1024M"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1G
      nodeSelector:
        devops.node.pool: static
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shipex-deployment
  namespace: devops-aos-prd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-shipex
    spec:
      containers:
      - name: shipex
        image: app-registry:30005/shipex:latest
        env:
        - name: CATALINA_OPTS
          value: "-Xms256M -Xmx1024M"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1G
      nodeSelector:
        devops.node.pool: static
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accountservice-deployment
  namespace: devops-aos-prd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-accountservice
    spec:
      containers:
      - name: accountservice
        image: app-registry:30005/accountservice:latest
        env:
        - name: CATALINA_OPTS
          value: "-Xms256M -Xmx1024M"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1G
      nodeSelector:
        devops.node.pool: static
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: devops-aos-prd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-frontend
    spec:
      containers:
      - name: frontend
        image: app-registry:30005/frontend-appdefender:latest
        env:
        - name: CATALINA_OPTS
          value: "-javaagent:/usr/local/tomcat/AppDefender_Agent/lib.latest/FortifyAgent.jar -Xms256M -Xmx2048M"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2G
      nodeSelector:
        devops.node.pool: static