
package ShipExServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShipExPortService",
                    targetNamespace = "https://www.AdvantageOnlineBanking.com/ShipEx/",
                    wsdlLocation = "http://localhost:8080/ShipEx/shipex.wsdl")
public class ShipExPortService
    extends Service
{

    private final static URL SHIPEXPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHIPEXPORTSERVICE_EXCEPTION;
    private final static QName SHIPEXPORTSERVICE_QNAME = new QName("https://www.AdvantageOnlineBanking.com/ShipEx/", "ShipExPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ShipEx/shipex.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHIPEXPORTSERVICE_WSDL_LOCATION = url;
        SHIPEXPORTSERVICE_EXCEPTION = e;
    }

    public ShipExPortService() {
        super(__getWsdlLocation(), SHIPEXPORTSERVICE_QNAME);
    }

    public ShipExPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHIPEXPORTSERVICE_QNAME, features);
    }

    public ShipExPortService(URL wsdlLocation) {
        super(wsdlLocation, SHIPEXPORTSERVICE_QNAME);
    }

    public ShipExPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHIPEXPORTSERVICE_QNAME, features);
    }

    public ShipExPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShipExPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShipExPort
     */
    @WebEndpoint(name = "ShipExPortSoap11")
    public ShipExPort getShipExPortSoap11() {
        return super.getPort(new QName("https://www.AdvantageOnlineBanking.com/ShipEx/", "ShipExPortSoap11"), ShipExPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShipExPort
     */
    @WebEndpoint(name = "ShipExPortSoap11")
    public ShipExPort getShipExPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.AdvantageOnlineBanking.com/ShipEx/", "ShipExPortSoap11"), ShipExPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHIPEXPORTSERVICE_EXCEPTION!= null) {
            throw SHIPEXPORTSERVICE_EXCEPTION;
        }
        return SHIPEXPORTSERVICE_WSDL_LOCATION;
    }

}
